# Dockerfile.snmpsim
FROM tandrup/snmpsim:latest
USER root

RUN sed -i \
    -e 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' \
    -e 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
    -e '/stretch-updates/ s/^/#/' \
    /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends curl snmp \
    && rm -rf /var/lib/apt/lists/*

# back to unprivileged
USER nobody:nogroup
