version: "2.4"
services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "192.168.1.10:172.18.0.2"
      - "192.168.1.11:172.18.0.2"
    environment:
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
       - logs-data:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    #restart: on-failure


  snmpsim:
    build:
      context: .
      dockerfile: Dockerfile.snmpsim
    image: tandrup/snmpsim
    user: root
    volumes:
      - ./snmp-sim/data:/usr/local/snmpsim/data
    ports:
      - "1161:1161/udp"
    command:
      - snmpsimd.py
      - --data-dir=/usr/local/snmpsim/data
      - --agent-udpv4-endpoint=0.0.0.0:1161
      - --logging-method=stdout
      - --process-user=nobody
      - --process-group=nogroup
    healthcheck:
      test: ["CMD-SHELL", "snmpwalk -v2c -c public 127.0.0.1:1161 .1.3.6.1.2.1.1.1.0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

# Top-level volumes section:
volumes:
  db_data:      # persists MySQL data
  logs-data:    # ← your new named volume for /app/logs
